# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-19 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank='true', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
