# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-19 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180519_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(default='N/A', max_length=4),
        ),
    ]
